name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      # only run the workflow if a change has happened within packages/container
      - 'packages/container/**'

defaults:
  run:
    # set the execution environment to within the packages/container folder
    working-directory: packages/container

jobs:
  build:
    # specify a Linux-based virtual machine
    runs-on: ubuntu-latest

    steps: 
    # load the code into the virtual machine, install dependencies and build
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build

    # deploy to AWS
    - uses: shinyinc/action-aws-cli@v1.2
    # sync the dist folder to the AWS S3 bucket
    - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-2"
